spring.application.name=demo
spring.thymeleaf.cache=false
server.error.include-message=always

# Perfil activo
spring.profiles.active=dev
#spring.profiles.active=dev

# Autenticación JWT
# En dev usa este valor; en prod se sobreescribe con la variable JWT_SECRET
app.jwt.secret=abc123==abc123==abc123==abc123==abc123==abc123==abc123==abc123==abc123==abc123==abc123==abc123==
app.jwt.expirationMs=86400000

# OpenRouter (IA)
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.chat.completions-path=/v1/chat/completions
spring.ai.openai.chat.options.model=google/gemini-2.5-flash
spring.ai.openai.chat.options.temperature=0.0
spring.ai.openai.chat.options.max-tokens=200