server.port=9000
server.error.include-stacktrace=always

# Configuración H2 (modo fichero, datos en ./dbfiles/)
spring.datasource.url=jdbc:h2:file:./dbfiles/demo
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Ejecuta data.sql DESPUÉS de que Hibernate cree las tablas
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true